# Generated by Django 5.0.1 on 2024-02-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tagy',
        ),
    ]
