# Generated by Django 5.0.1 on 2024-02-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_tag_tagy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagy',
            options={'verbose_name': 'Taggy', 'verbose_name_plural': 'Taggiess'},
        ),
        migrations.RenameField(
            model_name='tagy',
            old_name='sluf',
            new_name='slug',
        ),
    ]
