# Generated by Django 5.0.1 on 2024-02-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_tagy_options_rename_sluf_tagy_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagy',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
